server:
    port: 8081
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8080/eureka/
spring:
    application:
        name: gateway-service  
    cloud:
        gateway:
            discovery:
                locator:
                    lower-case-service-id: true
                    enabled: true
            routes:
            -   id: parameter-service-url
                uri: lb://parameter-service
                predicates:
                -   Path=/parameter/**
                filters:
                -   RewritePath=/parameter/(?<segment>.*), /$\{segment}
management:
    endpoint:
        service-registry:
            enabled: true